name: Continuous Integration Pipeline

on:
    push:
        paths:
            - data/**
            - project/**

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: 3.11

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint

            - name: Analysing the code with pylint
              # todo: just in data and project, not in exercise
              run: |
                pylint $(git ls-files 'data/*.py' 'project/*.py') 
    
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            
            - name: Install dependencies
              run: |
               python -m pip install --upgrade pip
               pip install -r ./data/requirements.txt
            
            - name: Run test
              run: |
               cd project
               chmod +x tests.sh
               ./tests.sh