name: Project test actions
on: 
    pull_request:
        types:
            - opened
            - edited
            - synchronize
        branches:
            - main

jobs:
  Project-test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
            path: main
      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: 3.11
      - name: Run tests
        run: |
          ./main/project/tests.sh
        