name: Project CI Test
on: 
  push:
    paths:
      - 'project/**'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  Pipeline_test:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./project
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python version
        uses: actions/setup-python@v4
        with:
            python-version: 3.8

      - name: Installing Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: pip install -r requirements.txt
          
      - name: Run tests
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          chmod +x ./tests.sh
          ./tests.sh
