name: Project CI Test
on: 
  push:
    paths:
      - 'project/**'
    branches:
      - main

jobs:
  Pipeline_test:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python version
        uses: actions/setup-python@v4
        with:
            python-version: 3.8

      - name: Installing Dependencies
        run: pip install -r requirements.txt

      - name: Kaggle Authenticator
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "kaggle.json"
          json: ${{ secrets.KAGGLE }}
              
      - name: Run tests
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
